### ISSUE TITLE
BPMN With Timer Error

### ISSUE THREAD

**Issue by kstan79** [bpmnServer/bpmn-server#187]
I notice after turn on timber (i use cycle method), then there is error appear as below (However, it is running) :
```
TypeError: Cannot read properties of null (reading 'slice')
    at parse (/Users/kstan/dev/products/simtrain-next/backend/node_modules/.pnpm/iso8601-duration@1.3.0/node_modules/iso8601-duration/lib/index.js:45:39)
    at Function.timeDue (/Users/kstan/dev/products/simtrain-next/backend/node_modules/.pnpm/bpmn-server@2.1.5_typedoc@0.25.12/node_modules/bpmn-server/src/server/Cron.ts:161:24)
    at Cron.scheduleProcess (/Users/kstan
```

**Comment by kstan79** [comment]
randomly appear and disappear, i close this issue until have better ideal

**Comment by ralphhanna** [comment]
I have added more debugging info in console.log
```ts
	static timeDue(expression,referenceDateTime) {
		if (expression) {
			let baseDate = new Date();
			let delay;
			const now = new Date().getTime();
			if (referenceDateTime) {
				baseDate = new Date(referenceDateTime);
			}
			try {
				delay = Cron.checkCron(expression, baseDate);
				if (delay) {
//					console.log(" expression " + expression + " base date" + baseDate+ " -> delay of " + delay + " sec " + delay / 60 + " min" + delay/3600 + " hours ");
				}
				else {
					delay = toSeconds(parse(expression));
					if (referenceDateTime) {
						delay += (referenceDateTime - now) / 1000;
					} 
//					console.log(" expression " + expression + " base date" + baseDate + " -> delay of " + delay + " sec " + delay / 60 + " min" + delay / 3600 + " hours ");
				}
			}
			catch (exc) {
				console.log(exc,'expression',expression);
				return null;
            }

			return delay;
		}
		return null;
    }
```
