### ISSUE TITLE
npm run setup encounter error

### ISSUE THREAD

**Issue by lling1105** [bpmnServer/bpmn-server#200]
error as below, did i miss some requirements?
```js
D:\bpmn-web>npm run setup

> bpmn-web@2.2.4 setup D:\bpmn-web
> ts-node src/scripts/setup.ts

D:\bpmn-web\node_modules\mongoose\node_modules\bson\lib\bson.cjs:143
        TextDecoderFatal ??= new TextDecoder('utf8', { fatal: true });
                         ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (D:\bpmn-web\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\bpmn-web\node_modules\mongoose\node_modules\mongodb\src\bson.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bpmn-web@2.2.4 setup: `ts-node src/scripts/setup.ts`
npm ERR! Exit status 1
npm ERR!
```

**Comment by ralphhanna** [comment]
No, you are not doing anything wrong, it may just be timing, package was in state of update.
Please run npm install again. it should work, if not , run npm update
Thanks
