### ISSUE TITLE
Server Shutdown - Unhandled Exception

### ISSUE THREAD

**Issue by MaheshkumarSundaram** [bpmnServer/bpmn-server#222]
Hi @ralphhanna,

Consider the following process,

![image](https://github.com/user-attachments/assets/f47eaa04-99e7-4c06-baa9-b2ec28b9f9fc)

**Steps to reproduce:**

- From `bpmn-web`'s UI, I start the above process.
- Now, I delete the started instance before the timer event expires
- The timer event is completed by Cron I guess and the associated query throws error:
   ```shell
   Exception: stack Error: query produced no items for {"items.id":"1bd38074-627a-43b1-97ed-40ba479f620e"}
      at Logger.error (F:\myApp\node_modules\bpmn-server\src\common\Logger.ts:120:15)
      at Engine.<anonymous> (F:\myApp\node_modules\bpmn-server\src\server\Engine.ts:289:17)
      at Generator.next (<anonymous>)
      at fulfilled (F:\myApp\node_modules\bpmn-server\dist\server\Engine.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
    F:\myApp\node_modules\bpmn-server\src\common\Logger.ts:120
    }
            
    Error: Error: query produced no items for {"items.id":"1bd38074-627a-43b1-97ed-40ba479f620e"}
      at Logger.error (F:\myApp\node_modules\bpmn-server\src\common\Logger.ts:120:15)
      at Engine.<anonymous> (F:\myApp\node_modules\bpmn-server\src\server\Engine.ts:575:22)
      at Generator.next (<anonymous>)
      at F:\myApp\node_modules\bpmn-server\dist\server\Engine.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (F:\myApp\node_modules\bpmn-server\dist\server\Engine.js:4:12)
      at Engine.exception (F:\myApp\node_modules\bpmn-server\dist\server\Engine.js:500:16)
      at Engine.<anonymous> (F:\myApp\node_modules\bpmn-server\src\server\Engine.ts:329:22)
      at Generator.next (<anonymous>)
      at fulfilled (F:\myApp\node_modules\bpmn-server\dist\server\Engine.js:5:58)
   ```

**Result:**
The server abruptly terminates due to the above exception.

I believe this issue is a regression but not sure from which version though.

Could you kindly look into this? Thanks.

**Comment by ralphhanna** [comment]
Thanks for reporting this, yes it is a regression, code restored.

Release 2.2.11 fixes this issue
